server:
  port: 8080
  error:
    whitelabel:
      enabled: false
logging:
  level:
    org.springframework.data.rest: DEBUG
spring:
  main:
    banner-mode: "off"
  devtools:
    restart:
      enabled: true
  h2:
    console.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    show-sql: true
    use_sql_comments: true
    format_sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect